# Generated by Django 3.1.3 on 2021-02-09 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0002_auto_20210209_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='image',
        ),
    ]
