# Generated by Django 3.1.3 on 2021-02-10 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0003_remove_customer_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='customer',
            new_name='User',
        ),
    ]
